#!/usr/bin/env bash
set -eu

REPO_ROOT="$(git rev-parse --show-toplevel)"
CODEOWNERS_FILE="$REPO_ROOT/CODEOWNERS"

# Directories to exclude (not plugins)
EXCLUDED_DIRS=".git .github Bin"

# Load existing CODEOWNERS entries into a temp file for lookup
EXISTING_ENTRIES=$(mktemp)
trap "rm -f $EXISTING_ENTRIES" EXIT

if [[ -f "$CODEOWNERS_FILE" ]]; then
  grep -v '^#' "$CODEOWNERS_FILE" | grep -v '^$' > "$EXISTING_ENTRIES" || true
fi

# Start building the CODEOWNERS file
cat > "$CODEOWNERS_FILE" <<'EOF'
# This file is auto-generated by the generate-codeowners workflow.
# Do not edit manually.
#
# Each plugin directory is owned by the first person who committed to it.

EOF

# Iterate over top-level directories that are plugins
for dir in "$REPO_ROOT"/*/; do
  dir_name=$(basename "$dir")

  # Skip excluded directories
  case " $EXCLUDED_DIRS " in
    *" $dir_name "*) continue ;;
  esac

  pattern="/$dir_name/"

  # If this plugin already has an entry in CODEOWNERS, keep it as-is
  existing_line=$(grep "^${pattern} " "$EXISTING_ENTRIES" 2>/dev/null || true)
  if [[ -n "$existing_line" ]]; then
    echo "$existing_line" >> "$CODEOWNERS_FILE"
    echo "  [KEPT]  $existing_line"
    continue
  fi

  # Find the first commit that touched this directory (oldest commit)
  # Use awk to get first line to avoid SIGPIPE with head
  first_author=$(git log --diff-filter=A --format='%ae' --reverse -- "$dir" 2>/dev/null | awk 'NR==1{print;exit}')

  if [[ -z "$first_author" ]]; then
    # Fallback: get the oldest commit author for this directory
    first_author=$(git log --format='%ae' --reverse -- "$dir" 2>/dev/null | awk 'NR==1{print;exit}')
  fi

  if [[ -z "$first_author" ]]; then
    echo "  [SKIP]  $pattern (no commits found)"
    continue
  fi

  # Try to extract the GitHub username from the email
  # GitHub noreply emails: user@users.noreply.github.com or 12345+user@users.noreply.github.com
  github_username=""
  if echo "$first_author" | grep -qE '^([0-9]+\+)?[^@]+@users\.noreply\.github\.com$'; then
    # Extract username from noreply email
    github_username=$(echo "$first_author" | sed -E 's/^([0-9]+\+)?([^@]+)@users\.noreply\.github\.com$/\2/')
  else
    # For non-noreply emails, get the author name from the same commit
    github_username=$(git log --format='%an' --reverse -- "$dir" 2>/dev/null | awk 'NR==1{print;exit}')
    # Replace spaces with hyphens
    github_username=$(echo "$github_username" | tr ' ' '-')
  fi

  if [[ -n "$github_username" ]]; then
    echo "$pattern @$github_username" >> "$CODEOWNERS_FILE"
    echo "  [NEW]   $pattern @$github_username"
  fi
done

echo ""
echo "CODEOWNERS file generated at $CODEOWNERS_FILE"
